import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, Banknote, Check, ChevronLeft, ChevronRight, CircleDollarSign, Flame, Home as HomeIcon, Medal, Menu, RotateCcw, ShieldAlert, Sparkles, Trophy, UserPlus, X } from 'lucide-react';
import { AddFriendFlow, FriendReportFlow } from './FriendScoreFlow';
import { EnhancedAddFriendFlow, EnhancedFriendReportFlow, EnhancedLeaderboard } from './FriendScoreLeaderboard';

const STORAGE_KEY = 'friendscore_friends';
const weights = { moneyReliability: 0.20, replyReliability: 0.10, planReliability: 0.15, foodLoyalty: 0.10, trustworthiness: 0.20, birthdayMemory: 0.05, helpfulness: 0.10, fiveMinuteAccuracy: 0.10 };
const fields = [
  ['moneyReliability', 'Money reliability', 'Pays you back, eventually. Usually.', 'Does not pay back', 'Would lend you money'],
  ['replyReliability', 'Reply reliability', 'How quickly do they answer the sacred green bubble?', 'Leaves you on read', 'Replies instantly'],
  ['planReliability', 'Plan reliability', 'Do plans happen, or are they fictional?', 'Cancels constantly', 'Always shows up'],
  ['foodLoyalty', 'Food loyalty', 'Would they share the last fry?', 'Steals your fries', 'Shares the last bite'],
  ['trustworthiness', 'Trustworthiness', 'Would you trust them with your secrets and snacks?', 'Absolutely not', 'With your life'],
  ['birthdayMemory', 'Birthday memory', 'Do they remember the day you spawned?', 'Never remembers', 'Plans a surprise'],
  ['helpfulness', 'Helpfulness', 'How likely are they to help you move?', 'Disappears on moving day', 'Brings a truck'],
  ['fiveMinuteAccuracy', '“5 minutes” accuracy', 'How literally should we take “I’m five minutes away”?', 'A geological five minutes', 'Actually five minutes']
];
const samples = [
  { id: 'FS-001', name: 'Maya Chen', moneyReliability: 94, replyReliability: 88, planReliability: 92, foodLoyalty: 76, trustworthiness: 97, birthdayMemory: 90, helpfulness: 86, fiveMinuteAccuracy: 72, borrowed: 120, returned: 120, createdAt: '2026-09-01T10:00:00.000Z' },
  { id: 'FS-002', name: 'Jordan Lee', moneyReliability: 71, replyReliability: 82, planReliability: 68, foodLoyalty: 91, trustworthiness: 78, birthdayMemory: 55, helpfulness: 74, fiveMinuteAccuracy: 44, borrowed: 80, returned: 60, createdAt: '2026-08-25T10:00:00.000Z' },
  { id: 'FS-003', name: 'Alex Rivera', moneyReliability: 36, replyReliability: 48, planReliability: 42, foodLoyalty: 63, trustworthiness: 57, birthdayMemory: 24, helpfulness: 46, fiveMinuteAccuracy: 18, borrowed: 200, returned: 25, createdAt: '2026-08-14T10:00:00.000Z' }
];

function getFriends() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved) && saved.length ? saved : samples; } catch { return samples; } }
function saveFriends(friends) { localStorage.setItem(STORAGE_KEY, JSON.stringify(friends)); }
function clamp(value) { return Math.max(0, Math.min(100, Math.round(value))); }
function calculateFriendScore(friend) {
  const repaymentScore = friend.borrowed > 0 ? Math.min(100, (friend.returned / friend.borrowed) * 100) : 100;
  const factors = { ...friend, moneyReliability: clamp((Number(friend.moneyReliability) * 0.7) + (repaymentScore * 0.3)) };
  const weighted = Object.entries(weights).reduce((sum, [key, weight]) => sum + Number(factors[key] || 0) * weight, 0);
  return { ...factors, weightedScore: Math.round(weighted), score: Math.max(0, Math.min(900, Math.round(weighted) * 9)), repaymentScore };
}
function rating(score) { if (score >= 800) return 'Soulmate Friend'; if (score >= 700) return 'Premium Friend'; if (score >= 600) return 'Standard Friend'; if (score >= 500) return 'High Risk Friend'; if (score >= 300) return 'Friendship Liability'; return 'Friendship Default'; }
function loanDecision(score) { if (score >= 750) return ['LOAN APPROVED', 'Your friend has passed the vibes-based underwriting process.', 'approved']; if (score >= 600) return ['APPROVED WITH CAUTION', 'Collateral may include one slice of pizza and a written promise.', 'caution']; if (score >= 400) return ['MANUAL REVIEW', 'A committee of one suspicious roommate will review this request.', 'review']; return ['LOAN REJECTED', 'The repayment history has entered witness protection.', 'rejected']; }
function explanation(friend, result) { const lines = []; if (result.trustworthiness >= 80) lines.push('Trustworthy enough for the aux cord.'); else lines.push('Trust is currently buffering.'); if (result.repaymentScore < 70) lines.push('Their repayment history is suspiciously creative.'); if (result.replyReliability < 50) lines.push('Replies arrive by carrier pigeon.'); if (result.planReliability >= 80) lines.push('Plans are more reliable than public transport.'); if (result.foodLoyalty < 50) lines.push('The last fry is not safe around them.'); if (result.fiveMinuteAccuracy < 50) lines.push('Their “five minutes” needs its own timezone.'); if (!lines.length) lines.push(`${friend.name} is statistically delightful and legally not a financial asset.`); return lines.join(' '); }
function roast(friend, result) { if (result.score >= 750) return `${friend.name} scored ${result.score}, which is annoyingly impressive. They are the friend equivalent of a premium rewards card.`; if (result.score >= 600) return `${friend.name} is a solid friend, provided you never ask what “on my way” means.`; if (result.score >= 400) return `${friend.name} has potential. Their friendship credit is currently held together by snacks and optimistic rounding.`; return `${friend.name} scored ${result.score}. The bank has frozen their friendship account pending several explanations.`; }
function formatMoney(value) { return `$${Number(value || 0).toLocaleString()}`; }

function Navbar() { const [open, setOpen] = useState(false); return <header className="fs-nav"><div className="fs-container fs-nav-inner"><Link className="fs-brand" to="/" onClick={() => setOpen(false)}><span className="fs-brand-mark">F</span><span>FRIENDSCORE<span className="tm">™</span></span></Link><button className="fs-menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={20} /> : <Menu size={20} />}</button><nav className={open ? 'fs-nav-links open' : 'fs-nav-links'}><NavLink to="/" end onClick={() => setOpen(false)}>Home</NavLink><NavLink to="/add" onClick={() => setOpen(false)}>Add Friend</NavLink><NavLink to="/leaderboard" onClick={() => setOpen(false)}>Leaderboard</NavLink></nav></div></header>; }
function Footer() { return <footer className="fs-footer"><div className="fs-container"><span>FRIENDSCORE™</span><span>Trust is temporary. Credit score is forever.</span><span>100% fake. 0% API.</span></div></footer>; }
function ScorePill({ score }) { return <span className="score-pill">{score}<small>/900</small></span>; }
function FriendRow({ friend }) { const result = calculateFriendScore(friend); return <Link className="friend-row" to={`/friend/${friend.id}`}><div className="friend-avatar">{friend.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><div><strong>{friend.name}</strong><span>{rating(result.score)}</span></div><ScorePill score={result.score} /><ArrowRight size={17} /></Link>; }
function Home({ friends }) { const sorted = friends.map((friend) => ({ friend, result: calculateFriendScore(friend) })).sort((a, b) => b.result.score - a.result.score); return <main className="fs-home"><section className="fs-container fs-hero"><div className="fs-hero-copy"><span className="fs-kicker"><Sparkles size={13} /> THE FINTECH NOBODY ASKED FOR</span><h1>FRIEND<span>SCORE</span><sup>™</sup></h1><p>Trust is temporary.<br /><em>Credit score is forever.</em></p><Link className="fs-button fs-button-primary" to="/add">Add Friend <UserPlus size={17} /></Link><div className="fs-stats"><span><strong>{friends.length}</strong> friends rated</span><span><strong>900</strong> max score</span><span><strong>0%</strong> seriousness</span></div></div><div className="fs-hero-card"><div className="fs-card-top"><span>FRIENDSCORE™</span><CircleDollarSign size={21} /></div><span className="fs-card-label">LATEST CREDIT CHECK</span><strong>742</strong><div className="fs-card-meter"><span style={{ width: '82%' }} /></div><div className="fs-card-meta"><span>PREMIUM FRIEND</span><span>82.4% APR*</span></div><small>*Absolutely made up.</small></div></section><section className="fs-container fs-sample-section"><div className="fs-section-heading"><div><span className="fs-kicker">THE FRIENDSHIP BUREAU</span><h2>Current accounts</h2></div><Link className="fs-text-link" to="/leaderboard">View leaderboard <ArrowRight size={15} /></Link></div><div className="fs-friend-list">{sorted.slice(0, 4).map(({ friend }) => <FriendRow key={friend.id} friend={friend} />)}</div></section></main>; }

function SliderField({ field, value, onChange }) { const [key, label, helper, low, high] = field; return <label className="fs-slider-field"><span className="fs-slider-title"><span><strong>{label}</strong><small>{helper}</small></span><b>{value}</b></span><input aria-label={label} type="range" min="0" max="100" value={value} onChange={(event) => onChange(key, Number(event.target.value))} /><span className="fs-slider-labels"><span>{low}</span><span>{high}</span></span></label>; }
function AddFriend({ onSave }) { const navigate = useNavigate(); const [friend, setFriend] = useState({ name: '', borrowed: 0, returned: 0, ...Object.fromEntries(fields.map(([key]) => [key, 70])) }); const update = (key, value) => setFriend((current) => ({ ...current, [key]: value })); const result = calculateFriendScore(friend); function submit(event) { event.preventDefault(); const saved = { ...friend, name: friend.name.trim() || 'Mystery Friend', id: `FS-${Math.floor(100 + Math.random() * 900)}`, createdAt: new Date().toISOString() }; onSave(saved); navigate(`/friend/${saved.id}`); } return <main className="fs-page fs-container"><div className="fs-page-heading"><span className="fs-kicker">NEW CREDIT APPLICATION</span><h1>Rate a <em>friend.</em></h1><p>Be fair. Be honest. Be prepared to lose a friend over the food loyalty question.</p></div><form className="fs-add-layout" onSubmit={submit}><section className="fs-form-card"><div className="fs-form-section"><label className="fs-name-field"><span>Friend name</span><input required value={friend.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Taylor Swift (the friend, probably)" /></label></div><div className="fs-form-section"><div className="fs-form-section-title"><span>Behavioral factors</span><small>Each answer becomes part of the credit report.</small></div>{fields.map((field) => <SliderField key={field[0]} field={field} value={friend[field[0]]} onChange={update} />)}</div><div className="fs-form-section money-section"><div className="fs-form-section-title"><span>Repayment history</span><small>Because friendship is complicated, but math is not.</small></div><div className="fs-money-grid"><label>Money borrowed<input type="number" min="0" value={friend.borrowed} onChange={(event) => update('borrowed', Number(event.target.value))} /></label><label>Money returned<input type="number" min="0" value={friend.returned} onChange={(event) => update('returned', Number(event.target.value))} /></label></div></div><button className="fs-button fs-button-primary fs-submit" type="submit">Calculate FriendScore <ArrowRight size={17} /></button></section><aside className="fs-live-card"><span className="fs-kicker">LIVE PREVIEW</span><h2>{friend.name || 'Your friend'}</h2><div className="fs-live-score"><strong>{result.score}</strong><span>/ 900</span></div><div className="fs-live-rating">{rating(result.score)}</div><div className="fs-live-bar"><span style={{ width: `${result.score / 9}%` }} /></div><p>Current weighted score: <b>{result.weightedScore}/100</b></p><div className="fs-live-loan"><Banknote size={17} /><span>Loan status</span><strong className={`loan-${loanDecision(result.score)[2]}`}>{loanDecision(result.score)[0]}</strong></div></aside></form></main>; }

function FriendDetail({ friends }) { const { id } = useParams(); const friend = friends.find((entry) => entry.id === id) || friends[0]; const result = calculateFriendScore(friend); const [roastText, setRoastText] = useState(''); const [loanAmount, setLoanAmount] = useState(100); const loan = loanDecision(result.score); return <main className="fs-page fs-container"><div className="fs-detail-top"><div><Link className="fs-back" to="/"><ChevronLeft size={16} /> All friends</Link><span className="fs-kicker">FRIENDSHIP CREDIT REPORT</span><h1>{friend.name}</h1><p>Account {friend.id} · Issued {new Date(friend.createdAt).toLocaleDateString()}</p></div><div className="fs-detail-score"><strong>{result.score}</strong><span>/ 900</span><b>{rating(result.score)}</b></div></div><section className="fs-report-banner"><div><span className="fs-kicker">CREDIT PROFILE</span><h2>{rating(result.score)}</h2><p>{explanation(friend, result)}</p></div><div className="fs-report-stamp"><ShieldAlert size={18} /><span>100% unofficial<br /><b>VERY OPINIONATED</b></span></div></section><div className="fs-detail-grid"><section className="fs-form-card"><div className="fs-section-heading"><div><span className="fs-kicker">FACTOR BREAKDOWN</span><h2>Why {result.score}?</h2></div><span className="fs-weight-note">Weighted average × 9</span></div>{fields.map(([key, label]) => <div className="fs-factor" key={key}><div><strong>{label}</strong><span>{result[key]}/100 · {Math.round(weights[key] * 100)}% weight</span></div><b>{(result[key] * weights[key]).toFixed(1)}</b><div className="fs-factor-bar"><span style={{ width: `${result[key]}%` }} /></div></div>)}<div className="fs-calculation"><span>Weighted average</span><strong>{result.weightedScore} × 9 = {result.score} / 900</strong></div></section><aside className="fs-side-stack"><section className="fs-loan-card"><span className="fs-kicker">FRIENDSHIP LOAN</span><h2>Would we lend them money?</h2><label>Requested amount<input type="number" min="0" value={loanAmount} onChange={(event) => setLoanAmount(Number(event.target.value))} /></label><div className={`fs-loan-decision ${loan[2]}`}><strong>{loan[0]}</strong><p>{loan[1]}</p><small>Request: {formatMoney(loanAmount)}</small></div></section><section className="fs-roast-card"><span className="fs-kicker"><Flame size={14} /> COMEDY DEPARTMENT</span><h2>Need a second opinion?</h2><button className="fs-button fs-button-dark" onClick={() => setRoastText(roast(friend, result))}>Roast My Friend <Flame size={16} /></button>{roastText && <p className="fs-roast-output">“{roastText}”</p>}</section></aside></div></main>; }

function Leaderboard({ friends }) { const rows = friends.map((friend) => ({ friend, result: calculateFriendScore(friend) })).sort((a, b) => b.result.score - a.result.score); return <main className="fs-page fs-container"><div className="fs-page-heading"><span className="fs-kicker"><Trophy size={14} /> FRIENDSHIP STOCK EXCHANGE</span><h1>Top <em>accounts.</em></h1><p>The friendships with the highest credit limit and lowest emotional overdraft.</p></div><section className="fs-leaderboard"><div className="fs-leader-head"><span>RANK</span><span>FRIEND</span><span>RATING</span><span>SCORE</span></div>{rows.map(({ friend, result }, index) => <div className="fs-leader-row" key={friend.id}><span className={`fs-rank rank-${index + 1}`}>{index < 3 ? <Medal size={17} /> : `0${index + 1}`}</span><Link className="friend-row" to={`/friend/${friend.id}`}><div className="friend-avatar">{friend.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><div><strong>{friend.name}</strong><span>{rating(result.score)}</span></div><ScorePill score={result.score} /><ArrowRight size={17} /></Link><span className="fs-leader-rating">{rating(result.score)}</span></div>)}</section></main>; }

export default function FriendScoreApp() { const [friends, setFriends] = useState(getFriends); const [newestId, setNewestId] = useState(null); useEffect(() => saveFriends(friends), [friends]); const onSave = (friend) => setFriends((current) => { const existing = current.find((item) => item.name.trim().toLowerCase() === friend.name.trim().toLowerCase()); const saved = existing ? { ...existing, ...friend, id: existing.id, createdAt: new Date().toISOString() } : friend; setNewestId(saved.id); return [saved, ...current.filter((item) => item.id !== saved.id && item.name.trim().toLowerCase() !== saved.name.trim().toLowerCase())]; }); return <div className="fs-app"><Navbar /><Routes><Route path="/" element={<Home friends={friends} />} /><Route path="/add" element={<EnhancedAddFriendFlow onSave={onSave} />} /><Route path="/friend/:id" element={<EnhancedFriendReportFlow friends={friends} newestId={newestId} />} /><Route path="/leaderboard" element={<EnhancedLeaderboard friends={friends} />} /><Route path="*" element={<Home friends={friends} />} /></Routes><Footer /></div>; }
