import { useState } from 'react';
import { ArrowRight, Banknote, Check, ChevronLeft, Copy, RotateCcw, ShieldAlert, Sparkles, X } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { RoastScene } from './RoastScene';

export const flowWeights = { money: 0.20, reply: 0.10, plans: 0.15, food: 0.10, trust: 0.20, birthday: 0.05, helpfulness: 0.10, fiveMinutes: 0.10 };
export const flowFields = [
  ['money', 'How reliable are they with borrowed money?', 'From “always pays back” to “what money?”'],
  ['reply', 'How quickly do they reply?', 'From “seen at 2:13 AM” to instant reply.'],
  ['plans', 'How often do they cancel plans?', '0 means never cancels. 100 means plans are fiction.'],
  ['food', 'Do they steal your food?', '0 means they share. 100 means protect your biryani.'],
  ['trust', 'How trustworthy are they?', 'Secrets, snacks, and your Netflix password.'],
  ['birthday', 'Do they remember your birthday?', 'The annual friendship audit.'],
  ['helpfulness', 'How helpful are they?', 'Would they help you move house?'],
  ['fiveMinutes', 'How accurate is their famous “5 minutes”?', '0 means geological time. 100 means actually five minutes.']
];
function clamp(value) { return Math.max(0, Math.min(100, Math.round(Number(value) || 0))); }
export function flowScore(friend) { const normalized = { ...friend, money: friend.money ?? friend.moneyReliability, reply: friend.reply ?? friend.replyReliability, plans: friend.plans ?? (friend.planReliability === undefined ? null : 100 - friend.planReliability), food: friend.food ?? (friend.foodLoyalty === undefined ? null : 100 - friend.foodLoyalty), trust: friend.trust ?? friend.trustworthiness, birthday: friend.birthday ?? friend.birthdayMemory, helpfulness: friend.helpfulness, fiveMinutes: friend.fiveMinutes ?? friend.fiveMinuteAccuracy }; const values = { ...normalized, plans: 100 - clamp(normalized.plans), food: 100 - clamp(normalized.food) }; const weightedScore = Math.round(Object.entries(flowWeights).reduce((sum, [key, weight]) => sum + clamp(values[key]) * weight, 0)); return { ...values, weightedScore, score: Math.max(0, Math.min(900, weightedScore * 9)) }; }
export function flowRating(score) { if (score >= 800) return 'Soulmate Friend'; if (score >= 700) return 'Premium Friend'; if (score >= 600) return 'Standard Friend'; if (score >= 500) return 'High Risk Friend'; if (score >= 300) return 'Friendship Liability'; return 'Friendship Default'; }
function loanFor(score) { return score >= 750 ? ['LOAN APPROVED', 'The friendship bank trusts this account.', 'approved'] : score >= 600 ? ['APPROVED WITH CAUTION', 'Collateral may include one slice of pizza.', 'caution'] : score >= 400 ? ['MANUAL REVIEW', 'A suspicious roommate committee will investigate.', 'review'] : ['LOAN REJECTED', 'The repayment history is in witness protection.', 'rejected']; }
function FlowSlider({ item, value, onChange }) { return <label className="fs-flow-slider"><span><strong>{item[1]}</strong><small>{item[2]}</small></span><b>{value === null ? '—' : value}</b><input aria-label={item[1]} type="range" min="0" max="100" value={value === null ? 50 : value} onChange={(event) => onChange(item[0], Number(event.target.value))} /><i><span>0</span><span>100</span></i></label>; }
export function AddFriendFlow({ onSave }) { const navigate = useNavigate(); const [friend, setFriend] = useState({ name: '', ...Object.fromEntries(flowFields.map(([key]) => [key, null])) }); const answered = flowFields.every(([key]) => friend[key] !== null); const update = (key, value) => setFriend((current) => ({ ...current, [key]: value })); function submit(event) { event.preventDefault(); if (!answered || !friend.name.trim()) return; const saved = { ...friend, name: friend.name.trim(), id: `FS-${Math.floor(100 + Math.random() * 900)}`, createdAt: new Date().toISOString() }; onSave(saved); navigate(`/friend/${saved.id}`); } return <main className="fs-page fs-container fs-assessment-flow"><div className="fs-page-heading"><span className="fs-kicker"><Sparkles size={13} /> FRIENDSHIP CREDIT CHECK</span><h1>Answer first.<br /><em>Judge later.</em></h1><p>No score appears until every question is answered and you click calculate. This is a judgment-free zone. Mostly.</p></div><form className="fs-question-form" onSubmit={submit}><section className="fs-form-card"><label className="fs-name-field fs-flow-name"><span>Friend name</span><input aria-label="Friend name" required value={friend.name} onChange={(event) => update('name', event.target.value)} placeholder="Who are we financially evaluating?" /></label><div className="fs-question-list">{flowFields.map((item) => <FlowSlider key={item[0]} item={item} value={friend[item[0]]} onChange={update} />)}</div><div className="fs-answer-status"><span>{flowFields.filter(([key]) => friend[key] !== null).length} / {flowFields.length} questions answered</span><span>{answered ? 'Ready for the verdict.' : 'Answer every slider to unlock calculation.'}</span></div><button className="fs-button fs-button-primary fs-calculate-button" type="submit" disabled={!answered || !friend.name.trim()}>CALCULATE FRIENDSCORE™ <ArrowRight size={17} /></button></section></form></main>; }
export function FriendReportFlow({ friends }) { const { id } = useParams(); const friend = friends.find((entry) => entry.id === id) || friends[0]; const result = flowScore(friend); const loan = loanFor(result.score); const [loanAmount, setLoanAmount] = useState(100); return <main className="fs-page fs-container fs-report-flow"><div className="fs-detail-top"><div><Link className="fs-back" to="/"><ChevronLeft size={16} /> All friends</Link><span className="fs-kicker">FRIENDSCORE™ CREDIT VERDICT</span><h1>{friend.name}</h1><p>Account {friend.id} · Issued {new Date(friend.createdAt).toLocaleDateString()}</p></div><div className="fs-detail-score fs-score-reveal"><strong>{result.score}</strong><span>/ 900</span><b>{flowRating(result.score)}</b></div></div><section className="fs-result-panel"><div className="fs-result-score"><span className="fs-kicker">FRIENDSCORE™</span><strong>{result.score}</strong><span>/ 900</span><h2>{flowRating(result.score)}</h2></div><div><span className="fs-kicker">THE OFFICIAL-ISH VERDICT</span><p>{result.trust >= 80 ? 'Trustworthy enough for the aux cord.' : 'Trust is currently buffering.'} {result.plans < 60 ? 'Plans are more of a loose suggestion.' : 'Plans actually survive the group chat.'}</p></div><div className="fs-result-stamp"><ShieldAlert size={18} /><span>NO BANKS INVOLVED<br /><b>JUST VIBES</b></span></div></section><RoastScene friend={friend.name} score={result.score} /><div className="fs-report-grid"><section className="fs-form-card fs-breakdown-card"><div className="fs-section-heading"><div><span className="fs-kicker">SCORE BREAKDOWN</span><h2>Why {result.score}?</h2></div><span className="fs-weight-note">Weighted average × 9</span></div>{flowFields.map(([key, label]) => <div className="fs-report-factor" key={key}><div><strong>{label}</strong><span>{result[key]} / 100 · {Math.round(flowWeights[key] * 100)}% weight</span></div><b>{(result[key] * flowWeights[key]).toFixed(1)}</b><div className="fs-factor-bar"><span style={{ width: `${result[key]}%` }} /></div></div>)}<div className="fs-calculation"><span>Final calculation</span><strong>{result.weightedScore} × 9 = {result.score} / 900</strong></div></section><aside className="fs-side-stack"><section className="fs-loan-card"><span className="fs-kicker"><Banknote size={14} /> FRIENDSHIP LOAN</span><h2>Would we lend them money?</h2><label>Requested amount<input aria-label="Requested amount" type="number" min="0" value={loanAmount} onChange={(event) => setLoanAmount(Number(event.target.value))} /></label><div className={`fs-loan-decision ${loan[2]}`}><strong>{loan[0]}</strong><p>{loan[1]}</p><small>Request: ${loanAmount.toLocaleString()}</small></div></section><Link className="fs-button fs-button-primary fs-another-button" to="/add"><RotateCcw size={16} /> ADD ANOTHER FRIEND</Link></aside></div></main>; }
