import { useState } from 'react';
import { ArrowRight, ChevronLeft, Medal, RotateCcw, ShieldAlert, Sparkles, Trophy } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { RoastScene } from './RoastScene';
import { flowFields, flowRating, flowScore, flowWeights } from './FriendScoreFlow';

export function EnhancedAddFriendFlow({ onSave }) {
  const navigate = useNavigate();
  const [friend, setFriend] = useState({ name: '', moneyBorrowed: 0, moneyReturned: 0, ...Object.fromEntries(flowFields.map(([key]) => [key, null])) });
  const answered = flowFields.every(([key]) => friend[key] !== null);
  const update = (key, value) => setFriend((current) => ({ ...current, [key]: value }));
  function submit(event) {
    event.preventDefault();
    if (!answered || !friend.name.trim()) return;
    const saved = { ...friend, name: friend.name.trim(), id: `FS-${Math.floor(100 + Math.random() * 900)}`, createdAt: new Date().toISOString() };
    onSave(saved);
    navigate(`/friend/${saved.id}`);
  }
  return <main className="fs-page fs-container fs-assessment-flow"><div className="fs-page-heading"><span className="fs-kicker"><Sparkles size={13} /> FRIENDSHIP CREDIT CHECK</span><h1>Answer first.<br /><em>Judge later.</em></h1><p>No score appears until every question is answered and you click calculate. This is a judgment-free zone. Mostly.</p></div><form className="fs-question-form" onSubmit={submit}><section className="fs-form-card"><label className="fs-name-field fs-flow-name"><span>Friend name</span><input aria-label="Friend name" required value={friend.name} onChange={(event) => update('name', event.target.value)} placeholder="Who are we financially evaluating?" /></label><div className="fs-question-list">{flowFields.map(([key, label, helper]) => <label className="fs-flow-slider" key={key}><span><strong>{label}</strong><small>{helper}</small></span><b>{friend[key] === null ? '—' : friend[key]}</b><input aria-label={label} type="range" min="0" max="100" value={friend[key] === null ? 50 : friend[key]} onChange={(event) => update(key, Number(event.target.value))} /><i><span>0</span><span>100</span></i></label>)}</div><div className="fs-money-inputs"><span className="fs-kicker">CASH DETAILS</span><div><label>Money borrowed<input aria-label="Money borrowed" type="number" min="0" value={friend.moneyBorrowed} onChange={(event) => update('moneyBorrowed', Number(event.target.value))} /></label><label>Money returned<input aria-label="Money returned" type="number" min="0" value={friend.moneyReturned} onChange={(event) => update('moneyReturned', Number(event.target.value))} /></label></div></div><div className="fs-answer-status"><span>{flowFields.filter(([key]) => friend[key] !== null).length} / {flowFields.length} questions answered</span><span>{answered ? 'Ready for the verdict.' : 'Answer every slider to unlock calculation.'}</span></div><button className="fs-button fs-button-primary fs-calculate-button" type="submit" disabled={!answered || !friend.name.trim()}>CALCULATE FRIENDSCORE™ <ArrowRight size={17} /></button></section></form></main>;
}

function moneyBorrowed(friend) { return Number(friend.moneyBorrowed ?? friend.borrowed ?? 0); }
function moneyReturned(friend) { return Number(friend.moneyReturned ?? friend.returned ?? 0); }
function moneyDebt(friend) { return Math.max(0, moneyBorrowed(friend) - moneyReturned(friend)); }
function repaymentRate(friend) { const borrowed = moneyBorrowed(friend); return borrowed > 0 ? Math.min(100, (moneyReturned(friend) / borrowed) * 100) : null; }
function riskLevel(score) { return score >= 800 ? 'Very Low' : score >= 700 ? 'Low' : score >= 600 ? 'Medium' : score >= 400 ? 'High' : 'Very High'; }
function scoreStatus(score) { return score >= 700 ? 'good' : score >= 500 ? 'watch' : 'risk'; }
function loanDecision(score) { return score >= 750 ? 'LOAN APPROVED' : score >= 600 ? 'APPROVED WITH CAUTION' : score >= 400 ? 'MANUAL REVIEW' : 'LOAN REJECTED'; }

function LeaderboardRows({ friends }) {
  const sorted = friends.map((friend) => ({ friend, result: flowScore(friend) })).sort((a, b) => b.result.score - a.result.score);
  return <div className="fs-credit-leaderboard" id="fs-leaderboard"><div className="fs-credit-leader-title"><div><span className="fs-kicker"><Trophy size={14} /> FRIENDSHIP CREDIT BUREAU</span><h2>Friendship leaderboard</h2></div><span className="fs-credit-leader-note">Sorted by score</span></div><div className="fs-credit-leader-head"><span>RANK</span><span>FRIEND</span><span>SCORE / RATING</span><span>RISK</span><span>CASH DETAILS</span></div>{sorted.map(({ friend, result }, index) => { const rate = repaymentRate(friend); return <Link className={`fs-credit-row ${index === 0 ? 'number-one' : ''}`} to={`/friend/${friend.id}`} key={friend.id}><span className={`fs-credit-rank rank-${index + 1}`}>{index < 3 ? <Medal size={17} /> : index + 1}</span><span className="fs-credit-friend"><span className="friend-avatar">{friend.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><span><strong>{friend.name}</strong><small>{flowRating(result.score)}</small></span></span><span className={`fs-credit-score ${scoreStatus(result.score)}`}>{result.score}<small>/900</small><em>{flowRating(result.score)}</em></span><span className={`fs-credit-risk ${scoreStatus(result.score)}`}>{riskLevel(result.score)}</span><span className="fs-money-details"><span>💰 ₹{moneyBorrowed(friend).toLocaleString()}</span><span>💵 ₹{moneyReturned(friend).toLocaleString()}</span><span className={moneyDebt(friend) > 0 ? 'has-debt' : 'paid'}>💸 ₹{moneyDebt(friend).toLocaleString()} · {moneyDebt(friend) > 0 ? 'Pending' : 'Fully Paid'}</span><span>📊 {rate === null ? 'N/A' : `${rate.toFixed(0)}%`}</span></span><span className="fs-credit-progress"><i style={{ width: `${result.score / 9}%` }} /></span></Link>; })}</div>;
}

function LeaderboardSummary({ friends }) { const scores = friends.map((friend) => flowScore(friend).score); const borrowed = friends.reduce((sum, friend) => sum + moneyBorrowed(friend), 0); const returned = friends.reduce((sum, friend) => sum + moneyReturned(friend), 0); const pending = Math.max(0, borrowed - returned); return <div className="fs-leader-summary"><div><span>Total Friends</span><strong>{friends.length}</strong></div><div><span>Average FriendScore</span><strong>{friends.length ? Math.round(scores.reduce((sum, score) => sum + score, 0) / friends.length) : 0}<small>/900</small></strong></div><div><span>Total Money Borrowed</span><strong>₹{borrowed.toLocaleString()}</strong></div><div><span>Total Money Returned</span><strong>₹{returned.toLocaleString()}</strong></div><div className={pending ? 'summary-debt' : 'summary-paid'}><span>Total Pending Debt</span><strong>₹{pending.toLocaleString()}</strong></div><div><span>Overall Repayment Rate</span><strong>{borrowed ? `${Math.min(100, (returned / borrowed) * 100).toFixed(0)}%` : 'N/A'}</strong></div></div>; }

export function EnhancedLeaderboard({ friends }) { return <main className="fs-page fs-container"><div className="fs-page-heading"><span className="fs-kicker"><Trophy size={14} /> FRIENDSHIP STOCK EXCHANGE</span><h1>Top <em>accounts.</em></h1><p>Sorted from highest score to lowest, with the full cash history on display.</p></div><LeaderboardSummary friends={friends} /><LeaderboardRows friends={friends} /></main>; }

export function EnhancedFriendReportFlow({ friends }) {
  const { id } = useParams();
  const friend = friends.find((entry) => entry.id === id) || friends[0];
  const result = flowScore(friend);
  const [loanAmount, setLoanAmount] = useState(100);
  const scrollToLeaderboard = () => document.getElementById('fs-leaderboard')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  return <main className="fs-page fs-container fs-report-flow"><div className="fs-detail-top"><div><Link className="fs-back" to="/"><ChevronLeft size={16} /> All friends</Link><span className="fs-kicker">FRIENDSCORE™ CREDIT VERDICT</span><h1>{friend.name}</h1><p>Account {friend.id} · Issued {new Date(friend.createdAt).toLocaleDateString()}</p></div><div className="fs-detail-score fs-score-reveal"><strong>{result.score}</strong><span>/ 900</span><b>{flowRating(result.score)}</b></div></div><section className="fs-result-panel"><div className="fs-result-score"><span className="fs-kicker">FRIENDSCORE™</span><strong>{result.score}</strong><span>/ 900</span><h2>{flowRating(result.score)}</h2></div><div><span className="fs-kicker">THE OFFICIAL-ISH VERDICT</span><p>{result.trust >= 80 ? 'Trustworthy enough for the aux cord.' : 'Trust is currently buffering.'} {result.plans < 60 ? 'Plans are more of a loose suggestion.' : 'Plans actually survive the group chat.'}</p></div><div className="fs-result-stamp"><ShieldAlert size={18} /><span>NO BANKS INVOLVED<br /><b>JUST VIBES</b></span></div></section><RoastScene friend={friend.name} score={result.score} /><div className="fs-report-grid"><section className="fs-form-card fs-breakdown-card"><div className="fs-section-heading"><div><span className="fs-kicker">SCORE BREAKDOWN</span><h2>Why {result.score}?</h2></div><span className="fs-weight-note">Weighted average × 9</span></div>{flowFields.map(([key, label]) => <div className="fs-report-factor" key={key}><div><strong>{label}</strong><span>{result[key]} / 100 · {Math.round(flowWeights[key] * 100)}% weight</span></div><b>{(result[key] * flowWeights[key]).toFixed(1)}</b><div className="fs-factor-bar"><span style={{ width: `${result[key]}%` }} /></div></div>)}<div className="fs-calculation"><span>Final calculation</span><strong>{result.weightedScore} × 9 = {result.score} / 900</strong></div></section><aside className="fs-side-stack"><div className="fs-loan-card"><span className="fs-kicker">FRIENDSHIP LOAN</span><h2>Would we lend them money?</h2><label>Requested amount<input aria-label="Requested amount" type="number" min="0" value={loanAmount} onChange={(event) => setLoanAmount(Number(event.target.value))} /></label><div className={`fs-loan-decision ${scoreStatus(result.score)}`}><strong>{loanDecision(result.score)}</strong><p>Request: ₹{loanAmount.toLocaleString()} · Decision based on friendship credit.</p></div></div><Link className="fs-button fs-button-primary fs-leader-button" to="#fs-leaderboard" onClick={(event) => { event.preventDefault(); scrollToLeaderboard(); }}><Trophy size={16} /> VIEW LEADERBOARD <ArrowRight size={15} /></Link><Link className="fs-button fs-button-dark fs-another-button" to="/add"><RotateCcw size={16} /> ADD ANOTHER FRIEND</Link></aside></div><LeaderboardRows friends={friends} /></main>;
}
